### ISSUE TITLE
Multimedia grid endpoint

### ISSUE THREAD

**Issue by BastekBielawski** [ergonode/backend#126]
**Goal**

As a user I would like to have the opportunity to see the list of available photos (multimedia)

**Todo**

- [x] Create Multimedia grid object with columns: name, image miniature, extension, mime type, size in bytes
- [x] Create new grid column type based on number. Format result number as file size B, KB, MB, GB etc
- [x] Create Multimedia grid endpoint
- [x] Create API tests

**Comment by MTheProgrammer** [comment]
I can take this task
