### ISSUE TITLE
Add channel module

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#328]
### Overview

Currently, it is not possible to select and configure export channels, so it is necessary to implement the Channels feature.

### Goal

- The solution should allow you to view, add, edit and delete channels.
- The channels should be able to handle products from the selected Segment.
- The channel model should be an abstract from which specific implementations will be created.

### Tasks

- [x] Adding channel module
- [x] Adding models of objects representing channels
- [x] Adding channel processing service
