### ISSUE TITLE
Extend condition set - add new conditions

### ISSUE THREAD

**Issue by WojFa** [ergonode/backend#335]
### Overview
Segmentation of the product must be more flexible and allow it to be limited by more conditions

### Goal
Add three new condition for product segmentation. 

### Tasks
- [x] Product belong to category
- [x] Product by SKU
- [x] Product template is
