### ISSUE TITLE
Add product collection module

### ISSUE THREAD

**Issue by wiewiurdp** [ergonode/backend#343]
### Overview
Currently it is not possible to group many products in collections (cross-sealing up-sealing ) so it is necessary to implement product collection module.

### Goal

- The solution should allow you to view, add, edit and delete collections.
- Many products could be added to collection.
- Collection should have visibility flag 
- Each product should have visibility flag

### Tasks

- [x] Adding collection module
- [x] Adding models of objects representing collections
- [x] Adding collection endpoints
- [x] Adding collection system attribute
