### ISSUE TITLE
Csv File import from Magento 1/2

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#367]
###Overview

Possibility to Import product form  magento 1 and magento 2  csv export file

###Tasks
- [x] Add core functionality
- [x] Add Source class
- [x] Add Transformer generator interface
- [x] Add Magento 1 csv compatible import
