### ISSUE TITLE
Add product with associations 

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#517]
### Overview

Possibility to make relation between products for creating  product groups or variants

### Goal

Add two new types of products
- Grouping product 
- Variable product

### Tasks

- [x] Add grouping product
- [x] Add Variable product
- [x] Extend communication enpoints
