### ISSUE TITLE
Shopware6 Export Module

### ISSUE THREAD

**Issue by wfajczyk** [ergonode/backend#528]
### Overview
New export functionality for Shopware6.

### Goal
Possibility to Export product to Shopware6

### Requirements
1. The Ergonode system should use the basic Shopware6 API.
2. Export under channel should send the required product information.
- name
- product number
- description - if provided
- list of categories  - if provided
- list of properties  - if provided
- list of custom field - if provided
- active status
- stock 
- tax 
- price
- multimedia - if provided
3. Export Property Group
4. Export Custom Field 
5. Export Multimedia
6. Synchronize Tax.
7. Synchronize Currency.

### Task

- [x] Export Simple Product Information 
- [x] Synchronize and mapping Product Tax
- [x] Synchronize and mapping Product Price
- [x] Synchronize and mapping Product Description
- [x] Synchronize and mapping Product Property Group
- [x] Synchronize and mapping Product Property Group Options
- [x] Synchronize and mapping Product Custom Field
- [x] Synchronize and mapping Multimedia
