### ISSUE TITLE
Multimedia managment

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#576]
# Overview

Need a simple multimedia/file management, and information

# Goal

Extend actual multimedia library to work with different file types,  present them on multimedia/resource grid and have possibility to see relations and information about them

# Task

- [x] Refactoring multimedia domain objects
- [x] Add multimedia grid
- [x] Add multimedia information endpoint
- [x] Add multimedia relation endpoint
