### ISSUE TITLE
Avatar resource separation

### ISSUE THREAD

**Issue by wiewiurdp** [ergonode/backend#612]
# Overview

After multimedia changes. Adding and retrieving avatar functionality needs to be separated from multimedia.

# Goal

Create a new avatar entity and change existing mechanics to use it

# Task

- [x] Create Avatar entity
- [x] Changing existing mechanics to use new entity
- [x] Add new avatar endpoints
- [x] Add deletion of avatar
