### ISSUE TITLE
Gallery and File attribute

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#625]
# Overview

The application should support work with many images
The application should be able to add any files to the product as attachments

#Task

- [x] Add gallery attribute
- [x] Add file collection attribute
- [x] Add File grid column
- [x] Add multimedia grid
