### ISSUE TITLE
Adding type to Category

### ISSUE THREAD

**Issue by wiewiurdp** [ergonode/backend#633]
# Overview

Add type to Category and separate AbstractCategory so Category mechanism would be more flexible.

# Task

- [x] Create AbstractCategory
- [x] Add type to category
- [x] Adding form provider
- [x] Add new endpoint for form configuration
