### ISSUE TITLE
Category management in the product

### ISSUE THREAD

**Issue by wfajczyk** [ergonode/backend#636]
### Overview
In order to expand category management in the product should be added endpoints.

### Task
- [x] Adding categories to the product 
- [x] Removing categories from the product
- [x] Display a list of categories in the product
