### ISSUE TITLE
Product with variants management optimization

### ISSUE THREAD

**Issue by wiewiurdp** [ergonode/backend#766]
### Overview
Currently adding and managing product with variants is not super efficient. 
Currently all selects in application are filled based on grid endpoints. This is problematic due to permission issues and it is slow as grid endpoints are more complex. 

### Goal

Detach adding binding attributes from product. It would be done on different tab with new endpoint.

### Tasks
- [x] Add endpoint for adding binding attribute to product
- [x] Remove binding attribute from create product with varints command
- [x] Create grid only with variants of given product
