### ISSUE TITLE
User activity flag

### ISSUE THREAD

**Issue by BastekBielawski** [ergonode/backend#77]
**Goals**
Add to user object activity flag

**Todo**
- [x] Active and deactive user event
- [x] Translation events for event log
- [x] Events and projections
- [x] Modify authenticator
