### ISSUE TITLE
Add batch product remove action

### ISSUE THREAD

**Issue by rprzedzik** [ergonode/backend#902]
### Overview
Mass product removal should be available

###Goal
Creation of a batch action mechanism for the mass product deletion

###Tasks

- [x] Add new batch action module
- [x] Add batch delete action endpoint
- [x] Add batch action information endpoint
- [x] Add batch delete action prcoess
